//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangNongSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Shipment
    {
        public int shipment_id { get; set; }
        public int warehouse_id { get; set; }
        public int product_id { get; set; }
        public int quantity { get; set; }
        public System.DateTime shipped_date { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual tbl_Products tbl_Products { get; set; }
        public virtual tbl_Warehouse tbl_Warehouse { get; set; }
    }
}
